# Generated by Django 5.1 on 2024-09-18 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opcoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.CharField(max_length=30)),
                ('votos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('p', 'Padrão'), ('l', 'Likert')], max_length=1)),
                ('titulo', models.CharField(max_length=200)),
                ('opcoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.opcoes')),
            ],
        ),
    ]
