# Generated by Django 5.1 on 2024-09-20 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdimensao',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='dimensao',
            name='subdimensao',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='parametro',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='opcoes',
        ),
        migrations.RemoveField(
            model_name='parametro',
            name='pergunta',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Dimensao',
        ),
        migrations.DeleteModel(
            name='Subdimensao',
        ),
        migrations.DeleteModel(
            name='Indicador',
        ),
        migrations.DeleteModel(
            name='Opcoes',
        ),
        migrations.DeleteModel(
            name='Parametro',
        ),
        migrations.DeleteModel(
            name='Pergunta',
        ),
    ]
