# Generated by Django 5.1 on 2024-09-20 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0002_remove_subdimensao_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Opcoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.CharField(max_length=30)),
                ('votos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='forms.indicador')),
            ],
        ),
        migrations.AddField(
            model_name='indicador',
            name='parametro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='forms.parametro'),
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('opcoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='forms.opcoes')),
            ],
        ),
        migrations.AddField(
            model_name='parametro',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='forms.pergunta'),
        ),
        migrations.CreateModel(
            name='Subdimensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='forms.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Dimensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('subdimensao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdimensoes', to='forms.subdimensao')),
            ],
        ),
    ]
