# Generated by Django 5.1 on 2024-09-19 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_remove_opcoes_criterio_remove_pergunta_criterio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcoes',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='forms.pergunta'),
        ),
    ]
