# Generated by Django 5.1 on 2024-09-20 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='opcoes',
        ),
        migrations.AddField(
            model_name='opcoes',
            name='pergunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='forms.pergunta'),
        ),
    ]
