# Generated by Django 5.1 on 2024-09-20 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_pergunta_opcoes_opcoes_pergunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='indicador',
        ),
        migrations.RemoveField(
            model_name='dimensao',
            name='subdimensao',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='parametro',
        ),
        migrations.RemoveField(
            model_name='parametro',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='subdimensao',
            name='categoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='subdimensao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdimensoes', to='forms.subdimensao'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='forms.categoria'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='indicador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='forms.indicador'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='parametro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='forms.parametro'),
        ),
        migrations.AddField(
            model_name='subdimensao',
            name='dimensao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dimensoes', to='forms.dimensao'),
        ),
    ]
